package com.runanywhere.kotlin_starter_example.kodent.engine

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object HealthReportExporter {

    fun exportAsText(result: CodeHealthResult, code: String, language: String): String {
        return buildString {
            appendLine("╔══════════════════════════════════════════════════════╗")
            appendLine("║          KODENT CODE HEALTH REPORT                  ║")
            appendLine("║          Generated by Kodent • Fully Offline        ║")
            appendLine("╚══════════════════════════════════════════════════════╝")
            appendLine()
            appendLine("Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}")
            appendLine("Language: $language")
            appendLine("Lines Analyzed: ${code.lines().size}")
            appendLine()

            appendLine("═══════════════════════════════════════")
            appendLine("  OVERALL HEALTH: ${result.overallScore}/100")
            appendLine("═══════════════════════════════════════")
            appendLine()

            appendLine("┌──────────────────────────────────────┐")
            appendLine("│  DIMENSION SCORES                    │")
            appendLine("├──────────────────────────────────────┤")
            appendLine("│  🐛 Bug Risk:      ${result.bugRisk}/10".padEnd(39) + "│")
            appendLine("│  ⚡ Performance:   ${result.performance}/10".padEnd(39) + "│")
            appendLine("│  🔒 Security:      ${result.security}/10".padEnd(39) + "│")
            appendLine("│  📖 Readability:   ${result.readability}/10".padEnd(39) + "│")
            appendLine("│  🧩 Complexity:    ${result.complexity}/10".padEnd(39) + "│")
            appendLine("└──────────────────────────────────────┘")
            appendLine()

            // Metrics
            if (result.metrics != null) {
                val m = result.metrics
                appendLine("┌──────────────────────────────────────┐")
                appendLine("│  CODE METRICS                        │")
                appendLine("├──────────────────────────────────────┤")
                appendLine("│  Total Lines:      ${m.totalLines}".padEnd(39) + "│")
                appendLine("│  Code Lines:       ${m.codeLines}".padEnd(39) + "│")
                appendLine("│  Comment Lines:    ${m.commentLines}".padEnd(39) + "│")
                appendLine("│  Blank Lines:      ${m.blankLines}".padEnd(39) + "│")
                appendLine("│  Functions:        ${m.functionCount}".padEnd(39) + "│")
                appendLine("│  Classes:          ${m.classCount}".padEnd(39) + "│")
                appendLine("│  Avg Func Length:  ${m.avgFunctionLength} lines".padEnd(39) + "│")
                appendLine("│  Max Nesting:      ${m.maxNestingDepth}".padEnd(39) + "│")
                appendLine("│  val/var Ratio:    ${m.valCount}/${m.varCount}".padEnd(39) + "│")
                appendLine("│  Comment Ratio:    ${m.commentPercentage}%".padEnd(39) + "│")
                appendLine("│  Cyclomatic:       ${m.cyclomaticComplexity}".padEnd(39) + "│")
                appendLine("└──────────────────────────────────────┘")
                appendLine()
            }

            // Best practices
            if (result.bestPractices.isNotEmpty()) {
                appendLine("BEST PRACTICES DETECTED:")
                result.bestPractices.forEach { practice ->
                    appendLine("  ✅ $practice")
                }
                appendLine()
            }

            // Issues
            if (result.issues.isNotEmpty()) {
                val criticalCount = result.issues.count { it.severity == IssueSeverity.CRITICAL }
                val highCount = result.issues.count { it.severity == IssueSeverity.HIGH }
                val mediumCount = result.issues.count { it.severity == IssueSeverity.MEDIUM }
                val lowCount = result.issues.count { it.severity == IssueSeverity.LOW }

                appendLine("SEVERITY BREAKDOWN:")
                if (criticalCount > 0) appendLine("  🔴 Critical: $criticalCount")
                if (highCount > 0) appendLine("  🟠 High: $highCount")
                if (mediumCount > 0) appendLine("  🟡 Medium: $mediumCount")
                if (lowCount > 0) appendLine("  🔵 Low: $lowCount")
                appendLine()

                appendLine("═══════════════════════════════════════")
                appendLine("  DETAILED FINDINGS")
                appendLine("═══════════════════════════════════════")
                appendLine()

                result.issues.forEachIndexed { i, issue ->
                    val severityIcon = when (issue.severity) {
                        IssueSeverity.CRITICAL -> "🔴 CRITICAL"
                        IssueSeverity.HIGH -> "🟠 HIGH"
                        IssueSeverity.MEDIUM -> "🟡 MEDIUM"
                        IssueSeverity.LOW -> "🔵 LOW"
                    }

                    appendLine("─── Issue #${i + 1} ─────────────────────────")
                    appendLine("Severity:    $severityIcon")
                    appendLine("Title:       ${issue.title}")
                    appendLine("Description: ${issue.description}")
                    appendLine()
                }
            } else {
                appendLine("✅ No issues found! Code is in excellent health.")
                appendLine()
            }

            appendLine("SUMMARY: ${result.summary}")
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("  END OF REPORT")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("Generated by Kodent — Offline AI Code Analyzer")
            appendLine("No data was transmitted. All analysis performed on-device.")
        }
    }
}