package com.runanywhere.kotlin_starter_example.kodent.engine

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object SecurityReportExporter {

    fun exportAsText(result: SecurityScanResult, code: String, language: String): String {
        return buildString {
            appendLine("╔══════════════════════════════════════════════════════╗")
            appendLine("║          KODENT SECURITY SCAN REPORT                ║")
            appendLine("║          Generated by Kodent • Fully Offline        ║")
            appendLine("╚══════════════════════════════════════════════════════╝")
            appendLine()
            appendLine("Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}")
            appendLine("Language: $language")
            appendLine("Lines Scanned: ${code.lines().size}")
            appendLine("Scan Time: ${result.scanTimeMs}ms")
            appendLine("Checks Run: ${result.totalChecks}")
            appendLine()

            // Grade & Score
            appendLine("═══════════════════════════════════════")
            appendLine("  SECURITY GRADE: ${result.grade}  (${result.score}/100)")
            appendLine("═══════════════════════════════════════")
            appendLine()

            // Summary counts
            appendLine("┌──────────────────────────────────────┐")
            appendLine("│  SEVERITY BREAKDOWN                  │")
            appendLine("├──────────────────────────────────────┤")
            if (result.criticalCount > 0)
                appendLine("│  🔴 CRITICAL:  ${result.criticalCount.toString().padEnd(24)}│")
            if (result.highCount > 0)
                appendLine("│  🟠 HIGH:      ${result.highCount.toString().padEnd(24)}│")
            if (result.mediumCount > 0)
                appendLine("│  🟡 MEDIUM:    ${result.mediumCount.toString().padEnd(24)}│")
            if (result.lowCount > 0)
                appendLine("│  🔵 LOW:       ${result.lowCount.toString().padEnd(24)}│")
            if (result.vulnerabilities.isEmpty())
                appendLine("│  ✅ No vulnerabilities found!        │")
            appendLine("└──────────────────────────────────────┘")
            appendLine()

            // OWASP Coverage
            if (result.owaspCoverage.isNotEmpty()) {
                appendLine("OWASP CATEGORIES DETECTED:")
                result.owaspCoverage.forEach { category ->
                    appendLine("  • $category")
                }
                appendLine()
            }

            // Summary
            appendLine("SUMMARY: ${result.summary}")
            appendLine()

            // Vulnerabilities
            if (result.vulnerabilities.isNotEmpty()) {
                appendLine("═══════════════════════════════════════")
                appendLine("  DETAILED FINDINGS")
                appendLine("═══════════════════════════════════════")
                appendLine()

                result.vulnerabilities.forEachIndexed { i, vuln ->
                    val severityIcon = when (vuln.severity) {
                        SecuritySeverity.CRITICAL -> "🔴 CRITICAL"
                        SecuritySeverity.HIGH -> "🟠 HIGH"
                        SecuritySeverity.MEDIUM -> "🟡 MEDIUM"
                        SecuritySeverity.LOW -> "🔵 LOW"
                    }

                    appendLine("─── Finding #${i + 1} ───────────────────────")
                    appendLine("Severity:    $severityIcon")
                    appendLine("Category:    ${vuln.category}")
                    appendLine("Title:       ${vuln.title}")
                    appendLine("Confidence:  ${vuln.confidence}")
                    if (vuln.lineNumber != null) {
                        appendLine("Location:    Line ${vuln.lineNumber}")
                    }
                    appendLine()
                    appendLine("Description: ${vuln.description}")
                    appendLine()
                    if (!vuln.codeSnippet.isNullOrBlank()) {
                        appendLine("Code:        ${vuln.codeSnippet}")
                        appendLine()
                    }
                    appendLine("Fix:         ${vuln.fix}")
                    if (vuln.owasp.isNotBlank()) {
                        appendLine("OWASP:       ${vuln.owasp}")
                    }
                    if (vuln.cwe.isNotBlank()) {
                        appendLine("CWE:         ${vuln.cwe}")
                    }
                    appendLine()
                }
            }

            // Footer
            appendLine("═══════════════════════════════════════")
            appendLine("  END OF REPORT")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("Generated by Kodent — Offline AI Security Scanner")
            appendLine("No data was transmitted. All analysis performed on-device.")
        }
    }

    fun exportAsJson(result: SecurityScanResult, code: String, language: String): String {
        return buildString {
            appendLine("{")
            appendLine("  \"report\": \"Kodent Security Scan\",")
            appendLine("  \"timestamp\": \"${SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault()).format(Date())}\",")
            appendLine("  \"language\": \"$language\",")
            appendLine("  \"linesScanned\": ${code.lines().size},")
            appendLine("  \"scanTimeMs\": ${result.scanTimeMs},")
            appendLine("  \"totalChecks\": ${result.totalChecks},")
            appendLine("  \"grade\": \"${result.grade}\",")
            appendLine("  \"score\": ${result.score},")
            appendLine("  \"summary\": \"${result.summary.replace("\"", "\\\"")}\",")
            appendLine("  \"counts\": {")
            appendLine("    \"critical\": ${result.criticalCount},")
            appendLine("    \"high\": ${result.highCount},")
            appendLine("    \"medium\": ${result.mediumCount},")
            appendLine("    \"low\": ${result.lowCount}")
            appendLine("  },")
            appendLine("  \"owaspCoverage\": [${result.owaspCoverage.joinToString(", ") { "\"${it.replace("\"", "\\\"")}\"" }}],")
            appendLine("  \"vulnerabilities\": [")

            result.vulnerabilities.forEachIndexed { i, vuln ->
                appendLine("    {")
                appendLine("      \"severity\": \"${vuln.severity}\",")
                appendLine("      \"category\": \"${vuln.category}\",")
                appendLine("      \"title\": \"${vuln.title.replace("\"", "\\\"")}\",")
                appendLine("      \"description\": \"${vuln.description.replace("\"", "\\\"")}\",")
                appendLine("      \"line\": ${vuln.lineNumber ?: "null"},")
                appendLine("      \"fix\": \"${vuln.fix.replace("\"", "\\\"")}\",")
                appendLine("      \"owasp\": \"${vuln.owasp.replace("\"", "\\\"")}\",")
                appendLine("      \"cwe\": \"${vuln.cwe}\",")
                appendLine("      \"confidence\": \"${vuln.confidence}\"")
                append("    }")
                if (i < result.vulnerabilities.size - 1) appendLine(",") else appendLine()
            }

            appendLine("  ]")
            appendLine("}")
        }
    }
}